server:
  port: 0

spring:
  application:
    name: api-serie
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017